Repository ros2/demos, pull requests merged in 2018-10, with the labels that each got.

#278 Add semicolons to all RCLCPP and RCUTILS macros.
  composition/src/api_composition.cpp
  composition/src/api_composition_cli.cpp
  composition/src/client_component.cpp
  composition/src/dlopen_composition.cpp
  composition/src/linktime_composition.cpp
  composition/src/listener_component.cpp
  composition/src/talker_component.cpp
  demo_nodes_cpp/src/parameters/list_parameters.cpp
  demo_nodes_cpp/src/parameters/list_parameters_async.cpp
  demo_nodes_cpp/src/parameters/parameter_events.cpp
  demo_nodes_cpp/src/parameters/parameter_events_async.cpp
  demo_nodes_cpp/src/parameters/set_and_get_parameters.cpp
  demo_nodes_cpp/src/parameters/set_and_get_parameters_async.cpp
  demo_nodes_cpp/src/services/add_two_ints_client.cpp
  demo_nodes_cpp/src/services/add_two_ints_client_async.cpp
  demo_nodes_cpp/src/timers/one_off_timer.cpp
  demo_nodes_cpp/src/timers/reuse_timer.cpp
  demo_nodes_cpp/src/topics/listener.cpp
  demo_nodes_cpp/src/topics/listener_best_effort.cpp
  demo_nodes_cpp/src/topics/talker.cpp
  demo_nodes_cpp_native/src/talker.cpp
  dummy_robot/dummy_sensors/src/dummy_laser.cpp
  image_tools/src/cam2image.cpp
  image_tools/src/showimage.cpp
  lifecycle/src/lifecycle_listener.cpp
  lifecycle/src/lifecycle_service_client.cpp
  lifecycle/src/lifecycle_talker.cpp
  logging_demo/src/logger_usage_component.cpp
Labels: in review

#276 adhere to new refactoring
  lifecycle/src/lifecycle_talker.cpp
Labels: in progress

#280 Fix lint warning from invalid escape sequences
  topic_monitor/topic_monitor/scripts/topic_monitor.py
Labels: in progress

#282 move wiki doc to pkg readme
  lifecycle/README.rst
Labels: documentation, in progress, in review
