Repository ros2/demos, pull requests merged in 2018-11, with the labels that each got.

#283 cleanup lifecycle demo
  lifecycle/CMakeLists.txt
  lifecycle/src/lifecycle_service_client.cpp
  lifecycle/src/lifecycle_service_client_py.py
Labels: in progress, in review

#284 use new error handling API from rcutils
  logging_demo/src/logger_config_component.cpp
  logging_demo/src/logger_usage_component.cpp
Labels: enhancement, in review

#285 Update package maintainer for logging_demo and topic_monitor
  logging_demo/package.xml
  topic_monitor/package.xml
Labels: in progress

#286 Update package maintainer
  demo_nodes_py/package.xml
  pendulum_control/package.xml
  pendulum_msgs/package.xml
Labels: in progress
