Repository ros2/demos, pull requests merged in 2018-06, with the labels that each got.

#237 Split ParameterVariant
  demo_nodes_cpp/src/parameters/list_parameters.cpp
  demo_nodes_cpp/src/parameters/list_parameters_async.cpp
  demo_nodes_cpp/src/parameters/parameter_events.cpp
  demo_nodes_cpp/src/parameters/parameter_events_async.cpp
  demo_nodes_cpp/src/parameters/ros2param.cpp
  demo_nodes_cpp/src/parameters/set_and_get_parameters.cpp
  demo_nodes_cpp/src/parameters/set_and_get_parameters_async.cpp
Labels: in review

#239 migrate launch -> launch.legacy
  composition/test/test_api_pubsub_composition.py.in
  composition/test/test_api_srv_composition.py.in
  composition/test/test_api_srv_composition_client_first.py.in
  composition/test/test_dlopen_composition.py.in
  composition/test/test_linktime_composition.py.in
  composition/test/test_manual_composition.py.in
  demo_nodes_cpp/test/test_executables_tutorial.py.in
  demo_nodes_cpp_native/test/test_executables_tutorial.py.in
  image_tools/test/test_executables_demo.py.in
  intra_process_demo/test/test_executables_demo.py.in
  lifecycle/launch/lifecycle_demo_launch.py
  logging_demo/test/test_logging_demo.py.in
  pendulum_control/test/test_pendulum_demo.py.in
  pendulum_control/test/test_pendulum_teleop.py.in
  topic_monitor/topic_monitor/launch_files/launch_depth_demo.py
  topic_monitor/topic_monitor/launch_files/launch_fragmentation_demo.py
  topic_monitor/topic_monitor/launch_files/launch_reliability_demo.py
Labels: in review

#243 use size_t in expose_cdr prs
  demo_nodes_cpp/src/topics/talker_serialized_message.cpp
Labels: in progress

#245 change in signature to get_service_name
  lifecycle/src/lifecycle_service_client.cpp
Labels: in review

#244 add talker_listener.launch.py new-style launch file
  demo_nodes_cpp/CMakeLists.txt
  demo_nodes_cpp/launch/services/add_two_ints.launch.py
  demo_nodes_cpp/launch/services/add_two_ints_async.launch.py
  demo_nodes_cpp/launch/topics/talker_listener.launch.py
  demo_nodes_cpp/launch/topics/talker_listener_best_effort.launch.py
  demo_nodes_cpp/package.xml
Labels: enhancement, in review

#185 Demo nodes for raw publish and subscribe
  demo_nodes_cpp/CMakeLists.txt
  demo_nodes_cpp/src/topics/allocator_tutorial.cpp
  demo_nodes_cpp/src/topics/listener_serialized_message.cpp
  demo_nodes_cpp/src/topics/talker_serialized_message.cpp
Labels: in review

#242 Fix potiential nullptr dereferenced issue in demo_nodes_cpp
  demo_nodes_cpp/src/services/add_two_ints_client.cpp
  demo_nodes_cpp/src/services/add_two_ints_client_async.cpp
  demo_nodes_cpp/src/services/add_two_ints_server.cpp
  demo_nodes_cpp/src/topics/listener.cpp
  demo_nodes_cpp/src/topics/talker.cpp
Labels: in review

#246 Topic monitor new launch
  topic_monitor/README.md
  topic_monitor/launch/depth_demo.launch.py
  topic_monitor/launch/fragmentation_demo.launch.py
  topic_monitor/launch/reliability_demo.launch.py
  topic_monitor/package.xml
  topic_monitor/setup.py
  topic_monitor/topic_monitor/launch_files/__init__.py
  topic_monitor/topic_monitor/launch_files/launch_depth_demo.py
  topic_monitor/topic_monitor/launch_files/launch_fragmentation_demo.py
  topic_monitor/topic_monitor/launch_files/launch_reliability_demo.py
Labels: in review

#251 remove obsolete ros2param executable
  demo_nodes_cpp/CMakeLists.txt
  demo_nodes_cpp/src/parameters/ros2param.cpp
Labels: in review

#252 Support remapping arguments to python nodes using argparse
  demo_nodes_py/demo_nodes_py/topics/listener_qos.py
  demo_nodes_py/demo_nodes_py/topics/talker_qos.py
  lifecycle/src/lifecycle_service_client_py.py
Labels: in review

#253 Pass remainder arguments only into rclpy.init
  demo_nodes_py/demo_nodes_py/topics/listener_qos.py
  demo_nodes_py/demo_nodes_py/topics/talker_qos.py
Labels: in progress, in review

#257 Reduce the publishing of the allocator_tutorial to 100Hz.
  demo_nodes_cpp/src/topics/allocator_tutorial.cpp
Labels: in review

#258 check that resolution is at least as big as burger
  image_tools/src/burger.cpp
Labels: bug, in review

#260 Fix linting errors in burger.cpp
  image_tools/src/burger.cpp
Labels: in review

#262 Convert launch files to new style
  dummy_robot/dummy_robot_bringup/launch/dummy_robot_bringup.launch.py
  dummy_robot/dummy_robot_bringup/launch/dummy_robot_bringup.py
  lifecycle/launch/lifecycle_demo.launch.py
  lifecycle/launch/lifecycle_demo_launch.py
Labels: in review

#263 [pendulum_*] claiming maintainership
  pendulum_control/package.xml
  pendulum_msgs/package.xml
Labels: in review
