Repository ros2/demos, pull requests merged in 2019-05, with the labels that each got.

#327 Corrected publish calls with shared_ptr signature
  composition/src/talker_component.cpp
  demo_nodes_cpp/src/topics/allocator_tutorial.cpp
  demo_nodes_cpp/src/topics/talker.cpp
  demo_nodes_cpp/src/topics/talker_serialized_message.cpp
  demo_nodes_cpp_native/src/talker.cpp
  dummy_robot/dummy_map_server/src/dummy_map_server.cpp
  dummy_robot/dummy_sensors/src/dummy_joint_states.cpp
  dummy_robot/dummy_sensors/src/dummy_laser.cpp
  image_tools/src/cam2image.cpp
  intra_process_demo/include/image_pipeline/camera_node.hpp
  intra_process_demo/include/image_pipeline/watermark_node.hpp
  intra_process_demo/src/cyclic_pipeline/cyclic_pipeline.cpp
  intra_process_demo/src/two_node_pipeline/two_node_pipeline.cpp
  lifecycle/src/lifecycle_talker.cpp
  logging_demo/src/logger_usage_component.cpp
  pendulum_control/include/pendulum_control/pendulum_controller.hpp
  pendulum_control/include/pendulum_control/pendulum_motor.hpp
  pendulum_control/include/pendulum_control/rtt_executor.hpp
  pendulum_control/src/pendulum_demo.cpp
  pendulum_control/src/pendulum_teleop.cpp
Labels: in review

#332 changes to avoid deprecated API's
  composition/src/listener_component.cpp
  composition/src/talker_component.cpp
  demo_nodes_cpp/src/topics/allocator_tutorial.cpp
  demo_nodes_cpp/src/topics/listener.cpp
  demo_nodes_cpp/src/topics/listener_best_effort.cpp
  demo_nodes_cpp/src/topics/listener_serialized_message.cpp
  demo_nodes_cpp/src/topics/talker.cpp
  demo_nodes_cpp/src/topics/talker_serialized_message.cpp
  demo_nodes_cpp_native/src/talker.cpp
  dummy_robot/dummy_map_server/src/dummy_map_server.cpp
  dummy_robot/dummy_sensors/src/dummy_joint_states.cpp
  dummy_robot/dummy_sensors/src/dummy_laser.cpp
  image_tools/src/cam2image.cpp
  image_tools/src/showimage.cpp
  intra_process_demo/include/image_pipeline/camera_node.hpp
  intra_process_demo/include/image_pipeline/image_view_node.hpp
  intra_process_demo/include/image_pipeline/watermark_node.hpp
  intra_process_demo/src/cyclic_pipeline/cyclic_pipeline.cpp
  intra_process_demo/src/two_node_pipeline/two_node_pipeline.cpp
  lifecycle/src/lifecycle_listener.cpp
  lifecycle/src/lifecycle_talker.cpp
  logging_demo/src/logger_usage_component.cpp
  pendulum_control/src/pendulum_demo.cpp
  pendulum_control/src/pendulum_logger.cpp
  pendulum_control/src/pendulum_teleop.cpp
Labels: in review

#333 add parameter_blackboard to make some tutorials easier
  demo_nodes_cpp/CMakeLists.txt
  demo_nodes_cpp/src/parameters/parameter_blackboard.cpp
Labels: in review

#335 Update expected type name in topic monitor
  topic_monitor/topic_monitor/scripts/topic_monitor.py
Labels: in review

#334 Fix deprecation warnings
  demo_nodes_py/demo_nodes_py/topics/listener.py
  demo_nodes_py/demo_nodes_py/topics/listener_qos.py
  demo_nodes_py/demo_nodes_py/topics/listener_serialized.py
  demo_nodes_py/demo_nodes_py/topics/talker.py
  demo_nodes_py/demo_nodes_py/topics/talker_qos.py
  topic_monitor/topic_monitor/scripts/data_publisher.py
  topic_monitor/topic_monitor/scripts/topic_monitor.py
Labels: in progress

#336 Add lifecycle rostest
  lifecycle/CMakeLists.txt
  lifecycle/package.xml
  lifecycle/test/test_lifecycle.py
Labels: in review

#320 QoS - Liveliness, Deadline, and Lifespan C++ Demos
  quality_of_service_demo/CMakeLists.txt
  quality_of_service_demo/README.md
  quality_of_service_demo/include/quality_of_service_demo/common_nodes.hpp
  quality_of_service_demo/package.xml
  quality_of_service_demo/src/common_nodes.cpp
  quality_of_service_demo/src/deadline.cpp
  quality_of_service_demo/src/lifespan.cpp
  quality_of_service_demo/src/liveliness.cpp
Labels: in review

#339 Add action_tutorials package
  action_tutorials/CMakeLists.txt
  action_tutorials/README.md
  action_tutorials/action/Fibonacci.action
  action_tutorials/bin/fibonacci_action_client.py
  action_tutorials/bin/fibonacci_action_server.py
  action_tutorials/package.xml
Labels: in review

#343 Add missing shebang to action tutorial executables
  action_tutorials/bin/fibonacci_action_client.py
  action_tutorials/bin/fibonacci_action_server.py
Labels: in review

#345 allow ESC/q/sigint to exit demo
  intra_process_demo/include/image_pipeline/image_view_node.hpp
Labels: in review

#348 use rate instead of thread::sleep to react to Ctrl-C
  lifecycle/src/lifecycle_service_client.cpp
Labels: enhancement, in review

#349 replace mesh with box
  dummy_robot/dummy_robot_bringup/launch/single_rrbot.urdf
Labels: in review

#355 update to use new parameter option names
  demo_nodes_cpp/src/parameters/parameter_blackboard.cpp
Labels: in review

#359 Use a positional argument for the quality of service demo.
  quality_of_service_demo/rclpy/quality_of_service_demo_py/common_nodes.py
Labels: in review

#360 update asciinema recordings
  lifecycle/README.rst
Labels: in review

#361 Fix memory leak in the dummy robot examples.
  dummy_robot/dummy_map_server/src/dummy_map_server.cpp
  dummy_robot/dummy_sensors/src/dummy_joint_states.cpp
  dummy_robot/dummy_sensors/src/dummy_laser.cpp
Labels: in review
