Repository ros2/demos, pull requests merged in 2019-04, with the labels that each got.

#319 Update for new rclcpp_components
  composition/CMakeLists.txt
  composition/include/composition/client_component.hpp
  composition/include/composition/listener_component.hpp
  composition/include/composition/server_component.hpp
  composition/include/composition/talker_component.hpp
  composition/package.xml
  composition/src/api_composition.cpp
  composition/src/api_composition_cli.cpp
  composition/src/client_component.cpp
  composition/src/dlopen_composition.cpp
  composition/src/linktime_composition.cpp
  composition/src/listener_component.cpp
  composition/src/manual_composition.cpp
  composition/src/server_component.cpp
  composition/src/talker_component.cpp
  composition/srv/LoadNode.srv
  logging_demo/CMakeLists.txt
  logging_demo/include/logging_demo/logger_config_component.hpp
  logging_demo/include/logging_demo/logger_usage_component.hpp
  logging_demo/package.xml
  logging_demo/src/logger_config_component.cpp
  logging_demo/src/logger_usage_component.cpp
  logging_demo/src/logging_demo_main.cpp
Labels: in progress

#321 Change use of deprecated rclcpp APIs
  demo_nodes_cpp/src/topics/allocator_tutorial.cpp
Labels: in progress

#241 Declare parameters
  demo_nodes_cpp/src/parameters/even_parameters_node.cpp
  demo_nodes_cpp/src/parameters/list_parameters.cpp
  demo_nodes_cpp/src/parameters/list_parameters_async.cpp
  demo_nodes_cpp/src/parameters/parameter_events.cpp
  demo_nodes_cpp/src/parameters/parameter_events_async.cpp
  demo_nodes_cpp/src/parameters/set_and_get_parameters.cpp
  demo_nodes_cpp/src/parameters/set_and_get_parameters_async.cpp
Labels: enhancement, in progress

#324 Add basic composition launch demo
  composition/CMakeLists.txt
  composition/launch/composition_demo.launch
  composition/package.xml
Labels: in progress

#323 Update constructor to const ref to NodeOptions
  composition/include/composition/client_component.hpp
  composition/include/composition/listener_component.hpp
  composition/include/composition/server_component.hpp
  composition/include/composition/talker_component.hpp
  composition/src/client_component.cpp
  composition/src/listener_component.cpp
  composition/src/server_component.cpp
  composition/src/talker_component.cpp
Labels: in review

#326 rename launch file, avoid redundant default actions, and output to screen
  composition/launch/composition_demo.launch.py
Labels: in review

#318 Migrate launch tests to new launch_testing features & API
  composition/CMakeLists.txt
  composition/package.xml
  composition/test/test_api_pubsub_composition.py.in
  composition/test/test_api_srv_composition.py.in
  composition/test/test_api_srv_composition_client_first.py.in
  composition/test/test_dlopen_composition.py.in
  composition/test/test_linktime_composition.py.in
  composition/test/test_manual_composition.py.in
  demo_nodes_cpp/CMakeLists.txt
  demo_nodes_cpp/package.xml
  demo_nodes_cpp/src/parameters/parameter_events.cpp
  demo_nodes_cpp/src/parameters/parameter_events_async.cpp
  demo_nodes_cpp/test/parameter_events.txt
  demo_nodes_cpp/test/parameter_events_async.txt
  demo_nodes_cpp/test/test_executables_tutorial.py.in
  demo_nodes_cpp_native/CMakeLists.txt
  demo_nodes_cpp_native/package.xml
  demo_nodes_cpp_native/test/test_executables_tutorial.py.in
  image_tools/CMakeLists.txt
  image_tools/package.xml
  image_tools/test/test_executables_demo.py.in
  intra_process_demo/CMakeLists.txt
  intra_process_demo/package.xml
  intra_process_demo/test/test_executables_demo.py.in
  logging_demo/CMakeLists.txt
  logging_demo/package.xml
  logging_demo/test/test_logging_demo.py.in
  pendulum_control/CMakeLists.txt
  pendulum_control/package.xml
  pendulum_control/test/test_pendulum_demo.py.in
  pendulum_control/test/test_pendulum_teleop.py.in
Labels: in review
